### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and 3.

### CODE REVIEW

**Comment by ndim** [comment]
As Python 2 is end of life, it makes sense to go further and completely drop Python 2.

**Comment by cclauss** [comment]
@msmeissn @ndim This is about as far as I can take this PR.  The base problem is that ['Pyrex`](https://pypi.org/project/Pyrex) will not pip install on Python 3.  I do not know autoconf/automake so I would be stumbling around in the dark to make `INSTALL` work.  If you can merge this PR and then get installation far enough where pytest will start to run the tests, then I could reengage.  I hope this helps.

**Comment by ndim** [comment]
So pyrex appears to be Python2 only, which means I do not even have it available here in almost-free-of-Python-2 Fedora 34.

As it is, `libgphoto2-python` appears to rely on `pyrexc` being available, so getting this to build appears to be non-trivial. It might even entail more or less a rewrite of at least the build system.

```
$ autoreconf -vis .
$ ./configure
[...]
checking for pyrexc... no
checking for pyrexc executable... 
configure: error: Fatal: pyrexc not found.

Get Pyrex from
  * your system's packages (recommended)
  * upstream at http://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/

```

**Comment by cclauss** [comment]
My sense is that `cffi` is the modern replacement for `Pyrex` so `python3-gphoto2 python3-gphoto2cffi` should be the right apt modules.

**Comment by ndim** [comment]
FTR, https://github.com/jbaiter/gphoto2-cffi is a third party software written and maintained outside of the gphoto project.

I do not know what kind and degree of collaboration has happened and is happening on gphoto2-cffi, as I have not been involved in gphoto very much within the last decade or so.

**Comment by msmeissn** [comment]
I think this might be the most current used python bindings:  https://github.com/jim-easterbrook/python-gphoto2

**Comment by cclauss** [comment]
https://github.com/jim-easterbrook/python-gphoto2/pull/115

**Pull request closed without merging**
